version: '2.1'
services:
  base_flink:
    build:
      context: ./flink/
      dockerfile: Dockerfile
    image: fk/flink-base-python

  # solution:
  #   build: ./java_solution
  #   image: fk/java-solution
  #   # command: "flink run -d /opt/ClickCountJob.jar --bootstrap.servers kafka:9092 --checkpointing --event-time"

  app1-builder:
    image: maven:3.8-eclipse-temurin-17
    volumes:
      - ./java_solution/app1:/app
      - jars:/jars
    working_dir: /app
    command: sh -c "mvn clean verify && cp target/*.jar /jars/"

  # Container final que reúne todos os JARs
  solution:
    image: fk/flink-base-python
    volumes:
      - jars:/opt/flink/solutions
    working_dir: /opt/flink/
    # command: "sleep infinity"
    depends_on:
      - base_flink

  jobmanager:
    image: fk/flink-base-python
    ports:
      - "18081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - jars:/opt/flink/solutions
    networks:
      - my-network
    depends_on:
      - base_flink
      
  taskmanager:
    image: decodable-examples/flink-with-connectors:1.17.1-scala_2.12-java11
    build:
      context: flink
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    volumes:
      - jars:/opt/flink/solutions
    networks:
      - my-network    

  sql-client:
    image: decodable-examples/flink-with-connectors:1.17.1-scala_2.12-java11
    build:
      context: flink
    command: bin/sql-client.sh -i /opt/flink/examples/flink-tables.sql
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    volumes:
      # - ./target/array-agg-0.1.jar:/opt/flink/lib/array-agg-0.1.jar
      - jars:/opt/flink/solutions
      - ./flink-tables.sql:/opt/flink/examples/flink-tables.sql
    networks:
      - my-network

  elasticsearch:
    image: elastic/elasticsearch:7.17.9
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - my-network


  postgres:
    image: quay.io/debezium/example-postgres:2.7
    # image: postgres:11-alpine
    # image: postgis/postgis:16-3.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=study
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
    volumes:
      # - ./postgres/inventory.sql:/docker-entrypoint-initdb.d/inventory.sql
      - ./postgres/public_inventory.sql:/docker-entrypoint-initdb.d/public_inventory.sql
      - ./postgres/postgresql.conf.sample:/usr/share/postgresql/postgresql.conf.sample
    networks:
      - my-network

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.7
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 9644:9644
      - 29092:29092
    networks:
      - my-network  

networks:
  my-network:
    name: array-agg-network

# Definição do volume compartilhado
volumes:
  jars: